# permissions for end users to edit vms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-editor-role
rules:
- apiGroups:
  - cloud.ibm.com
  resources:
  - vms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.ibm.com
  resources:
  - vms/status
  verbs:
  - get
