# permissions for end users to view vms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-viewer-role
rules:
- apiGroups:
  - cloud.ibm.com
  resources:
  - vms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.ibm.com
  resources:
  - vms/status
  verbs:
  - get
